### ISSUE TITLE
Fix Start Game Button

### ISSUE THREAD

**Issue by AnimezKishan** [AnimezKishan/Bubble-Game#1]
_Start Game Button is showing some unusual behaviour where you have to click the button twice to restart the game._

**Comment by SandipGyawali** [comment]
I am interested in contributing. Can you assign me the issue. @AnimezKishan

**Comment by AnimezKishan** [comment]
Sure! @SandipGyawali

**Comment by SandipGyawali** [comment]
@AnimezKishan  I just checked the project and i was wondering that if I could add the restart button instead of the two things happening with the start button. What do you say ?

**Comment by AnimezKishan** [comment]
@SandipGyawali I was thinking of same. But if you could manage to do in the same button. That is, if the game is already started, the innerHTML of button changes to Refresh which reloads the page and then you have to restart the game by again pressing the start game button.

**Comment by SandipGyawali** [comment]
@AnimezKishan  yea already did it you can check my pull request
